### 1. Login as Admin first to receive cookie
# @name adminLogin
POST http://localhost:7777/api/auth/login
Content-Type: application/json

{
  "email": "admintest2@example.com",
  "password": "password1234"
}

### 2. Get Admin Dashboard Overview
GET http://localhost:7777/api/admin-dashboard/overview

### 3. Get Admin Dashboard Orders
GET http://localhost:7777/api/admin-dashboard/orders

### 4. Get Admin Dashboard Sales
GET http://localhost:7777/api/admin-dashboard/sales
