### 1. Login as User first to receive cookie
# @name userLogin
POST http://localhost:7777/api/auth/login
Content-Type: application/json

{
  "email": "usertest1@example.com",
  "password": "password1234"
}

### 2. Get My Address
GET http://localhost:7777/api/user-dashboard/my-address

### 3. Create or Update My Address
PUT http://localhost:7777/api/user-dashboard/my-address
Content-Type: application/json

{
  "recipientName": "My Father",
  "phone": "0848748456",
  "street": "เชียงใหม่-ลำพูน",
  "district": "เมือง",
  "province": "เชียงใหม่",
  "postcode": "50845"
}

### 4. Delete My Address
DELETE http://localhost:7777/api/user-dashboard/my-address
