### 1. Login (User)
# @name login
POST http://localhost:7777/api/auth/login
Content-Type: application/json

{
  "email": "admintest2@example.com",
  "password": "password1234"
}

### 2. ดูรายการที่อยู่
GET http://localhost:7777/api/addresses/

### 3. เพิ่มที่อยู่ใหม่
# @name addAddress
POST http://localhost:7777/api/addresses/
Content-Type: application/json

{
  "name": "บ้าน",
  "detail": "123/45 หมู่บ้านสวยงาม ถ.สุขุมวิท แขวงคลองเตย เขตคลองเตย กรุงเทพฯ 10110",
  "isDefault": true
}

### 4. ลบที่อยู่
DELETE http://localhost:7777/api/addresses/ไอดีที่อยู่
